import Foundation

/// The OpenCode plugin TapQ installs, rendered for a specific hook-executable path.
///
/// The plugin is embedded as source text rather than carried as an SPM resource on
/// purpose: `scripts/package-runtime-app.sh` assembles `TapQRuntime.app` by copying the
/// built executables alone, so a `.copy` resource bundle would be absent from the packaged
/// runtime — exactly where `tapq integration opencode install` is normally run — and
/// `Bundle.module` would trap there. Embedding also makes installation, repair detection,
/// and idempotence a plain string comparison against `render(hookCommand:)`.
///
/// The plugin deliberately does the least it can: it normalizes OpenCode bus events onto
/// TapQ's relay envelope, shells out to `tapq-opencode-hook`, and applies the returned
/// decision through OpenCode's own permission API. All policy, broker authentication, and
/// speech rendering stay in Swift. Its only import is `node:child_process`, which is
/// available under both the Bun and Node builds of OpenCode; `Bun.$` deliberately is not
/// used because it is `undefined` under the Node build.
///
/// Sources for the surface this plugin uses, verified against OpenCode `v1.18.15`:
/// - Plugin input (`client`, `directory`, `serverUrl`) and the `event` hook:
///   https://opencode.ai/docs/plugins/
/// - `permission.asked` payload:
///   https://github.com/anomalyco/opencode/blob/dev/packages/schema/src/v1/permission.ts
/// - `POST /permission/{requestID}/reply` with `{ reply, message? }`, and the deprecated
///   `POST /session/{id}/permissions/{permissionID}` with `{ response }`:
///   https://opencode.ai/docs/server/
/// - The reply enum `"once" | "always" | "reject"` and the V1 SDK method
///   `postSessionIdPermissionsPermissionId` injected as `client`:
///   https://github.com/anomalyco/opencode/blob/dev/packages/sdk/js/src/gen/sdk.gen.ts
/// - `session.idle` (deprecated) and `session.status`:
///   https://github.com/anomalyco/opencode/blob/dev/packages/schema/src/session-status-event.ts
///
/// The `permission.ask` *hook* in `@opencode-ai/plugin` is intentionally not used: it is
/// declared in the plugin types but no OpenCode code path triggers it
/// (https://github.com/anomalyco/opencode/issues/7006, still open). Observing the
/// `permission.asked` *event* and answering over the API is the mechanism that runs today.
public enum OpenCodePluginSource {
    /// First line of every plugin TapQ writes. Ownership detection and the uninstall path
    /// both key off this marker, so a plugin the user wrote themselves is never rewritten.
    public static let marker = "// tapq-opencode-plugin"

    /// Bumped whenever the generated plugin changes in a way that needs reinstalling.
    /// It appears in the marker line, so `status` reports a stale plugin as `partial` and
    /// a rerun of `install` repairs it.
    public static let version = 1

    public static func markerLine() -> String {
        "\(marker) v\(version) — generated by `tapq integration opencode install`. Do not edit."
    }

    /// True when `contents` was written by some version of TapQ.
    public static func isManagedPlugin(_ contents: String) -> Bool {
        contents.hasPrefix(marker)
    }

    /// Renders the plugin for `hookCommand`, whose absolute path is baked in exactly as the
    /// Codex installer bakes its command into `hooks.json`. Moving the checkout or runtime
    /// app therefore makes the plugin stale, which `status` reports and `install` repairs.
    public static func render(hookCommand: String) -> String {
        """
        \(markerLine())
        //
        // Relays OpenCode permission prompts to the local TapQ broker and applies the
        // hands-free decision. Every failure path is silent: OpenCode keeps its own
        // on-screen prompt and stays fully in control.
        //
        // Remove with `tapq integration opencode uninstall`.

        import { spawn } from "node:child_process"

        const HOOK = \(javaScriptStringLiteral(hookCommand))
        const RELAY_VERSION = 1

        // Must outlast the broker's own interaction budget so a slow hands-free answer is
        // still delivered; the hook fails open on its own socket timeout before this.
        const PERMISSION_TIMEOUT_MS = 265000
        const NOTIFY_TIMEOUT_MS = 10000

        // OpenCode still emits the deprecated `session.idle` alongside its `session.status`
        // replacement, so the same completion would otherwise be announced twice.
        const IDLE_DEDUPE_MS = 5000
        const lastIdle = new Map()

        // Runs the TapQ hook and resolves with its parsed stdout, or null on any failure.
        // A null result means "TapQ has no answer", which leaves OpenCode's prompt alone.
        function runHook(payload, timeoutMs) {
          return new Promise((resolve) => {
            let child
            try {
              child = spawn(HOOK, { stdio: ["pipe", "pipe", "ignore"] })
            } catch {
              resolve(null)
              return
            }

            let settled = false
            let stdout = ""
            const finish = (value) => {
              if (settled) return
              settled = true
              clearTimeout(timer)
              resolve(value)
            }
            const timer = setTimeout(() => {
              try { child.kill("SIGKILL") } catch {}
              finish(null)
            }, timeoutMs)

            child.on("error", () => finish(null))
            child.stdout.on("data", (chunk) => { stdout += chunk })
            child.on("close", (code) => {
              if (code !== 0 || stdout.trim() === "") {
                finish(null)
                return
              }
              try {
                finish(JSON.parse(stdout))
              } catch {
                finish(null)
              }
            })

            try {
              child.stdin.end(JSON.stringify(payload))
            } catch {
              finish(null)
            }
          })
        }

        // Answers a pending OpenCode permission. Tries the current permission route first,
        // then the injected SDK client, whose only permission method targets the older
        // session-scoped route. Either one resolves the prompt; both failing leaves it on
        // screen, which is the intended fallback.
        async function respond(input, sessionID, permissionID, reply, message) {
          if (input.serverUrl) {
            try {
              const url = new URL(
                "/permission/" + encodeURIComponent(permissionID) + "/reply",
                input.serverUrl,
              )
              const body = message ? { reply: reply, message: message } : { reply: reply }
              const result = await fetch(url, {
                method: "POST",
                headers: { "content-type": "application/json" },
                body: JSON.stringify(body),
              })
              if (result.ok) return true
            } catch {
              // Fall through to the SDK client below.
            }
          }

          const client = input.client
          const method = client && client.postSessionIdPermissionsPermissionId
          if (typeof method === "function") {
            try {
              await method.call(client, {
                path: { id: sessionID, permissionID: permissionID },
                body: { response: reply },
              })
              return true
            } catch {
              return false
            }
          }
          return false
        }

        function permissionPayload(event, directory) {
          const properties = event.properties || {}
          const sessionID = properties.sessionID
          const permissionID = properties.id
          if (typeof sessionID !== "string" || typeof permissionID !== "string") return null

          // `permission` is the current field name for the kind; `type` was its name in
          // older releases. An unrecognized kind still relays and is spoken generically.
          const kind =
            typeof properties.permission === "string"
              ? properties.permission
              : typeof properties.type === "string"
                ? properties.type
                : "unknown"

          return {
            tapq_relay_version: RELAY_VERSION,
            hook_event_name: "permission.asked",
            session_id: sessionID,
            permission_id: permissionID,
            permission: kind,
            metadata:
              properties.metadata && typeof properties.metadata === "object"
                ? properties.metadata
                : {},
            directory: typeof directory === "string" ? directory : null,
          }
        }

        async function handlePermission(input, event) {
          const payload = permissionPayload(event, input.directory)
          if (payload === null) return

          const result = await runHook(payload, PERMISSION_TIMEOUT_MS)
          const decision = result && result.decision
          const behavior = decision && decision.behavior
          if (behavior !== "allow" && behavior !== "deny") return

          // A hands-free answer is scoped to the single prompt it was spoken for, so the
          // remembered reply OpenCode also accepts is deliberately never sent.
          await respond(
            input,
            payload.session_id,
            payload.permission_id,
            behavior === "allow" ? "once" : "reject",
            behavior === "deny" && typeof decision.message === "string"
              ? decision.message
              : undefined,
          )
        }

        function idleSessionID(event) {
          const properties = event.properties || {}
          if (typeof properties.sessionID !== "string") return null
          if (event.type === "session.idle") return properties.sessionID
          const status = properties.status
          if (status && status.type === "idle") return properties.sessionID
          return null
        }

        async function handleIdle(input, event) {
          const sessionID = idleSessionID(event)
          if (sessionID === null) return

          const now = Date.now()
          const previous = lastIdle.get(sessionID)
          if (previous !== undefined && now - previous < IDLE_DEDUPE_MS) return
          lastIdle.set(sessionID, now)

          await runHook(
            {
              tapq_relay_version: RELAY_VERSION,
              hook_event_name: "session.idle",
              session_id: sessionID,
              directory: typeof input.directory === "string" ? input.directory : null,
            },
            NOTIFY_TIMEOUT_MS,
          )
        }

        export const TapQ = async (input) => {
          return {
            event: async ({ event }) => {
              if (!event || typeof event.type !== "string") return
              // Deliberately not awaited: a hands-free answer can take minutes and the
              // OpenCode event bus must stay responsive throughout.
              if (event.type === "permission.asked") {
                handlePermission(input, event).catch(() => {})
              } else if (event.type === "session.idle" || event.type === "session.status") {
                handleIdle(input, event).catch(() => {})
              }
            },
          }
        }

        """
    }

    /// Emits a double-quoted JavaScript string literal. Escaping is explicit rather than
    /// JSON-encoded so the generated file stays readable and byte-stable across platforms.
    static func javaScriptStringLiteral(_ value: String) -> String {
        var escaped = ""
        escaped.reserveCapacity(value.count + 2)
        for character in value.unicodeScalars {
            switch character {
            case "\\": escaped += "\\\\"
            case "\"": escaped += "\\\""
            case "\n": escaped += "\\n"
            case "\r": escaped += "\\r"
            case "\t": escaped += "\\t"
            // U+2028/U+2029 terminate a line in JavaScript source but not in Swift.
            case "\u{2028}": escaped += "\\u2028"
            case "\u{2029}": escaped += "\\u2029"
            case let scalar where scalar.value < 0x20 || scalar.value == 0x7F:
                escaped += String(format: "\\u%04X", scalar.value)
            default: escaped.unicodeScalars.append(character)
            }
        }
        return "\"\(escaped)\""
    }
}
